#!/bin/sh
# ezfetch - the lightest and simplest *fetch out there.
# LonelyPyxel && camonater62
# 
# Version 2.0c
#
# This modified version is maintained at:
#  https://github.com/camonater62/ezfetch


# here begins the fetch madness ########################################################################
NC='\e[0m' # No color
HOST="$(hostname)" #Gets Hostname
KERNEL="$(uname -mrs)" #Gets Kernel
SHELL="$(ls -l /proc/$$/exe | sed 's%.*/%%')" #Gets Shell
    if [ -n "$DISPLAY" ]; then #Credit to Mitya on IRC for this func.			# Gets the window Manager
	id="$(xprop -root -notype | \awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" 
	wm="$(xprop -id "$id" -notype -f _NET_WM_NAME 8t)"
	wm="${wm/*_NET_WM_NAME = }"
	wm="${wm/\"}"
	wm="${wm/\"*}"
fi

#source: https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script
OS=$(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]') # Gets the distro
ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/') # Gets the bit version of the distro
VERSION=$(awk '/DISTRIB_RELEASE=/' /etc/*-release | sed 's/DISTRIB_RELEASE=//' | sed 's/[.]0/./') # Gets version release date
RAM=$(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }') # Gets the amount of RAM and usage
CPU=$(awk 'BEGIN{FS=":"} /model name/ { print $2; exit }' /proc/cpuinfo | awk 'BEGIN{FS=" @"; OFS="\n"} { print $1; exit }') # Gets the CPU model

if [ -z "$OS" ]; then
    OS=$(awk '{print $1}' /etc/*-release | tr '[:upper:]' '[:lower:]')
fi

if [ -z "$VERSION" ]; then
    VERSION=$(awk '{print $3}' /etc/*-release)
fi

if [ "$XDG_CURRENT_DESKTOP" = "" ]						# Gets DE
then
  desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
else
  desktop=$XDG_CURRENT_DESKTOP
fi

desktop=${desktop,,}  # convert to lower case

# make sure args are correct ###########################################################################

if [ $# = 0 ] || [ $# = 1 ] || [ $# = 9 ]; then
  GOOD=1
else
  echo "incorrect # of args"
  exit 0
fi

# help #################################################################################################

if [ "$1" == "-h" ]; then
  echo -e "ezfetch v1.6"
  echo -e "lonelypyxel && camonater62"
  echo -e ""
  echo -e "How to Use:"
  echo -e "by default everything is turned on"
  echo -e "0 = off" 
  echo -e "1 = on"
  echo -e "(and yes I know this is a horrible way to do it)"
  echo -e ""
  echo -e "order: distro release kernel host wm/de shell cpu ram color"
  echo -e "ex (only cpu and ram): ./ezfetch 0 0 0 0 0 0 1 1"  
  echo -e "if all you want is color then you only need 1 arg"
  echo -e "the arg for color can go from 0-9"
  echo -e "0:no color 1:black 2:red 3:green 4:brown 5:blue"   
  echo -e "6:magenta 7:cyan 8:light gray 9:white"
exit 0
fi

# old version ##########################################################################################

if [ "$1" == "-o" ]; then
echo -e " E \033[1;37m██\033[0;30m██ ${NC}Distro:         $OS $ARCH bit
 Z \033[0;34m██\033[1;34m██ ${NC}Release:        $VERSION 
 F \033[0;32m██\033[1;32m██ ${NC}Kernel:         $KERNEL
 E \033[0;36m██\033[1;36m██ ${NC}Host:           $HOST
 T \033[0;31m██\033[1;31m██ ${NC}WM / DE:        $wm / $desktop
 C \033[0;35m██\033[1;35m██ ${NC}Shell:          $SHELL
 H \033[0;33m██\033[1;33m██ ${NC}CPU:           $CPU
1.5\033[1;30m██\033[0;37m██ ${NC}Ram:            $RAM
${NC}"
exit 0
fi

# term colors ##########################################################################################

if [ "$1" == "-t" ]; then
echo -e "\033[1;37m██\033[0;30m██\033[0;34m██\033[1;34m██
\033[0;32m██\033[1;32m██\033[0;36m██\033[1;36m██
\033[0;31m██\033[1;31m██\033[0;35m██\033[1;35m██
\033[0;33m██\033[1;33m██\033[1;30m██\033[0;37m██
${NC}"
exit 0
fi

# box ##################################################################################################

if [ "$1" == "-b" ]; then
echo -e "\e[0;30m╔\e[0;31m═══\e[0;32m╗
\e[0;37m║ \e[1;30mo \e[0;33m║
\e[0;36m╚\e[0;35m═══\e[0;34m╝
${NC}"
exit 0
fi

# color madness ########################################################################################

# no color
if [ "$9" == 0 ] || [ "$#" == 1 ] && [ "$1" == 0 ] || [ "$#" == 0 ]; then
  echo -e "${NC}		EZFETCH"
fi
# black
if [ "$9" == 1 ] || [ "$#" == 1 ] && [ "$1" == 1 ]; then
  echo -e "\e[0;30m		EZFETCH"
fi
# red
if [ "$9" == 2 ] || [ "$#" == 1 ] && [ "$1" == 2 ]; then
  echo -e "\e[0;31m		EZFETCH"
fi
# green
if [ "$9" == 3 ] || [ "$#" == 1 ] && [ "$1" == 3 ]; then
  echo -e "\e[0;32m		EZFETCH"
fi
# brown
if [ "$9" == 4 ] || [ "$#" == 1 ] && [ "$1" == 4 ]; then
  echo -e "\e[0;33m		EZFETCH"
fi
# blue
if [ "$9" == 5 ] || [ "$#" == 1 ] && [ "$1" == 5 ]; then
  echo -e "\e[0;34m		EZFETCH"
fi
# magenta
if [ "$9" == 6 ] || [ "$#" == 1 ] && [ "$1" == 6 ]; then
  echo -e "\e[0;35m		EZFETCH"
fi
# cyan
if [ "$9" == 7 ] || [ "$#" == 1 ] && [ "$1" == 7 ]; then
  echo -e "\e[0;36m		EZFETCH"
fi
#light gray
if [ "$9" == 8 ] || [ "$#" == 1 ] && [ "$1" == 8 ]; then
  echo -e "\e[0;37m		EZFETCH"
fi
# white
if [ "$9" == 9 ] || [ "$#" == 1 ] && [ "$1" == 9 ]; then
  echo -e "\e[1;30m		EZFETCH"
fi

# Here's where it displays everything! #################################################################

echo -e "
\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95"

if [ "$1" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Distro:         $OS $ARCH bit"
fi
if [ "$2" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Release:        $VERSION"
fi
if [ "$3" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Kernel:         $KERNEL"
fi
if [ "$4" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Host:           $HOST"
fi
if [ "$5" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "WM / DE:        $wm / $desktop"
fi
if [ "$6" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Shell:          $SHELL"
fi
if [ "$7" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "CPU:           $CPU"
fi
if [ "$8" == 1 ] || [ "$#" == 0 ] || [ "$#" == 1 ]; then
  echo -e "Ram:            $RAM"
fi

# finish it off
echo -e "\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95\xe2\x80\x95${NC}"
